# Generated by Django 5.0.14 on 2026-05-27 18:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PerfilKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('birth_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de verificación'), ('VERIFIED', 'Verificado'), ('BLOCKED', 'Bloqueado'), ('SELF_EXCLUDED', 'Auto-excluido')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('self_excluded_until', models.DateTimeField(blank=True, null=True)),
                ('daily_deposit_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('weekly_deposit_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('monthly_deposit_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('limits_last_raised_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil KYC',
                'verbose_name_plural': 'Perfiles KYC',
                'db_table': 'perfil_kyc',
            },
        ),
        migrations.CreateModel(
            name='RegistroIdempotencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.SmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_idempotencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Idempotencia',
                'verbose_name_plural': 'Registros de Idempotencia',
                'db_table': 'registro_idempotencia',
            },
        ),
        migrations.AddConstraint(
            model_name='registroidempotencia',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_idempotencia_user_key'),
        ),
    ]
