# Generated by Django 4.2.30 on 2026-05-27 06:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('sport', models.CharField(max_length=50)),
                ('starts_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('LIVE', 'En vivo'), ('FINISHED', 'Finalizado'), ('SUSPENDED', 'Suspendido'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evento',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('1X2', 'Resultado (1X2)'), ('OU', 'Más/Menos (Over/Under)'), ('BTTS', 'Ambos equipos anotan'), ('HCAP', 'Handicap asiático')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='markets.event')),
            ],
            options={
                'db_table': 'mercado',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('odds', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='markets.market')),
            ],
            options={
                'db_table': 'seleccion',
            },
        ),
    ]
