# Generated by Django 4.2.30 on 2026-05-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('Fútbol', 'Fútbol'), ('Baloncesto', 'Baloncesto'), ('Tenis', 'Tenis'), ('Vóley', 'Vóley'), ('Béisbol', 'Béisbol')], default='Fútbol', max_length=50),
        ),
    ]
