# Generated by Django 5.0.14 on 2026-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_alter_event_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='away_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='home_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
