# Generated by Django 5.0.14 on 2026-05-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_event_away_score_event_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='live_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
