version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - .:/app
    env_file:
      - path: .env
        required: false
    environment:
      - EMAIL_HOST=mailpit
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8003:8003"
    depends_on:
      - db
      - redis
      - mailpit

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - path: .env
        required: false
    environment:
      - EMAIL_HOST=mailpit
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
      - mailpit

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=fairbet
      - POSTGRES_USER=fairbet
      - POSTGRES_PASSWORD=fairbet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  postgres_data:
