import os

with open('config/settings.py', 'r') as f:
    content = f.read()

top_content = '''"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-3w5!uttuk%&px1k5!v8wlvnj0-6dw5sr*t_wy(%we2^&jbuwk='
DEBUG = True
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'channels',
    'apps.markets',
    'apps.accounts',
]

AUTH_USER_MODEL = 'accounts.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'
'''

new_content = top_content + content.split("ROOT_URLCONF = 'config.urls'")[1]
with open('config/settings.py', 'w') as f:
    f.write(new_content)
