# Generated by Django 5.0.14 on 2026-05-27 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18)),
                ('payout', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('total_odds', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PLACED', 'Colocada'), ('WON', 'Ganada'), ('LOST', 'Perdida'), ('VOID', 'Anulada'), ('CASHED_OUT', 'Retirada (Cash-out)')], default='PENDING', max_length=15)),
                ('bet_type', models.CharField(choices=[('SINGLE', 'Simple'), ('ACCA', 'Combinada')], default='SINGLE', max_length=10)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apuesta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('odds_at_placement', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.bet')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='markets.selection')),
            ],
            options={
                'db_table': 'apuesta_seleccion',
                'unique_together': {('bet', 'selection')},
            },
        ),
    ]
