# Generated by Django 6.0.4 on 2026-05-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.BigIntegerField(unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('payload_canonical', models.TextField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['sequence'], name='audit_sequence_idx'), models.Index(fields=['event_type'], name='audit_event_type_idx'), models.Index(fields=['created_at'], name='audit_created_at_idx')],
            },
        ),
    ]
