# Generated by Django 5.0.14 on 2026-05-28 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('SHARED_IP', 'Inicio de sesión desde IP compartida'), ('DEP_WD', 'Depósito y retiro rápido sin juego'), ('PATTERN', 'Patrón sospechoso de apuestas o KYC'), ('LIMIT_EXCEEDED', 'Exceso de límite de depósito')], max_length=50)),
                ('evidence', models.JSONField()),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('FALSO_POSITIVO', 'Falso Positivo')], default='PENDIENTE', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad Sospechosa',
                'verbose_name_plural': 'Actividades Sospechosas',
                'db_table': 'actividad_sospechosa',
                'ordering': ['-detected_at'],
            },
        ),
    ]
