# Generated by Django 5.0.14 on 2026-05-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0003_bonuscampaign_userbonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransactionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Movimiento de pago',
                'verbose_name_plural': 'Movimientos de pagos (Depósitos / Retiros)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet.transaction',),
        ),
    ]
