# Generated by Django 6.0.4 on 2026-05-28 00:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from inspect import signature
from django.conf import settings
from django.db import migrations, models


def check_constraint(*, condition, name):
    constraint_kwargs = {"name": name}
    if "condition" in signature(models.CheckConstraint).parameters:
        constraint_kwargs["condition"] = condition
    else:
        constraint_kwargs["check"] = condition
    return models.CheckConstraint(**constraint_kwargs)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('INTERNAL_TRANSFER', 'Internal transfer'), ('BET_PLACEMENT', 'Bet placement'), ('BET_PAYOUT', 'Bet payout'), ('BET_LOSS', 'Bet loss'), ('BET_REFUND', 'Bet refund'), ('CASHOUT', 'Cashout')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('USER_WALLET', 'User wallet'), ('HOUSE', 'House'), ('PENDING_BETS', 'Pending bets'), ('BONUS', 'Bonus')], max_length=32)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='wallet_tx_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction'], name='ledger_tx_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'account_owner'], name='ledger_account_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['created_at'], name='ledger_created_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=check_constraint(condition=models.Q(('amount__gt', Decimal('0.0000'))), name='ledger_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=check_constraint(condition=models.Q(models.Q(('account', 'HOUSE'), ('account_owner__isnull', True)), models.Q(('account__in', ['USER_WALLET', 'PENDING_BETS', 'BONUS']), ('account_owner__isnull', False)), _connector='OR'), name='ledger_account_owner_required'),
        ),
    ]
