# Generated by Django 6.0.4 on 2026-05-28 09:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_walletidempotencyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('bonus_type', models.CharField(choices=[('WELCOME', 'Welcome'), ('FIRST_DEPOSIT', 'First deposit'), ('RESPONSIBLE_GAMING', 'Responsible gaming')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('is_active', models.BooleanField(default=True)),
                ('required_bets_count', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='bonus_campaign_code_idx'), models.Index(fields=['bonus_type'], name='bonus_campaign_type_idx'), models.Index(fields=['is_active'], name='bonus_campaign_active_idx')],
                'constraints': [models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.0000'))), name='bonus_campaign_amount_gt_zero')],
            },
        ),
        migrations.CreateModel(
            name='UserBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=16)),
                ('required_bets_count', models.PositiveIntegerField(default=5)),
                ('completed_bets_count', models.PositiveIntegerField(default=0)),
                ('is_withdrawable', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='wallet.bonuscampaign')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_redemptions', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='user_bonus_user_status_idx'), models.Index(fields=['campaign'], name='user_bonus_campaign_idx'), models.Index(fields=['redeemed_at'], name='user_bonus_redeemed_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'campaign'), name='user_bonus_user_campaign_uniq'), models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.0000'))), name='user_bonus_amount_gt_zero')],
            },
        ),
    ]
